# Project information

site_name: Using ML with Amazon SageMaker & GuardDuty to identify anomalous traffic
site_description: This workshop shows how you can use an IP-based machine learning algorithm with Amazon SageMaker to augment and enrich findings from AWS Security services such as Amazon GuardDuty. You'll learn how to load the notebook in SageMaker, train the model, and score findings to determine abnormality of the activity.
site_author: 'aws-security-workshops@amazon.com'
site_url: 'http://ml-threat-detection.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/aws-ml-detection-workshop'
repo_url: 'https://github.com/aws-samples/aws-ml-detection-workshop'

# Copyright
copyright: '<a href="https://aws.amazon.com/privacy/" target="_blank">Privacy</a> | <a href="https://aws.amazon.com/terms/" target="_blank">Site terms</a> | &copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://awssecworkshops.com
    - icon: fontawesome/solid/shield-alt
      link: https://aws.amazon.com/security/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/awssecurityinfo?lang=en
    - icon: fontawesome/solid/rss-square
      link: https://aws.amazon.com/blogs/security/

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Workshop: 'index.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
